### PR TITLE
Fix docs: routes import

### PR DESCRIPTION
**Pull request by dhruvdutt**
Fixes FABPage import inside `routes.tsx`.

Also fixes all components that imports `"app/js/components/Page"`

There are still many compilation errors like this with `tsc`:
```
[at-loader] Checking finished with 972 errors
[at-loader] ../packages/base/node_modules/@types/react/index.d.ts:2852:13 
    TS2403: Subsequent variable declarations must have the same type.  Variable 'svg' must be of type 'SVGProps<SVGSVGElement>', but here has type 'SVGProps<SVGSVGElement>'. 
```

### CODE REVIEW

**Comment by hardtack** [comment]
Thank you for your pull request.
It's hard to find that kind of mistakes since filesystem of macOS is case insensitive. :(

Anyway, could you tell me your development environment? I've never meet that kind of errors.

You have to use [lerna](https://lernajs.io) to load `@react-mdc` dependencies from local.

Did you try
``` shell
$ lerna bootstrap
```
Before starting build?

**Comment by dhruvdutt** [comment]
OS: Kubuntu 17.04 x64, Kernel 4.10.0-22 generic
Env: Node v7.10.0, npm 4.6.1, lerna 2.0.0-rc.5

I did `lerna bootstrap` and then `npm start` inside `docs` directory. Everything is successfully executed but can't see any server running or hosting docs locally. Where/how to see them?

Also, I figured out the errors about `'SVGProps<SVGSVGElement>'` were because of something related to `@types/react` versioning. Read more about it here: [#11922](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11922).
I did a clean installation of everything again and it was resolved.

Btw, `npm run watch` seems to be too heavy on resources. It hogs up at least 7 GB RAM out of total 8. Maybe, it's because of `--concurrency=50`.

Also, I would like to know your dev env and the reason behind not using package-lock.json and yarn-lock.json

**Comment by hardtack** [comment]
@dhruvdutt 
I added `package-lock.json` to git.
The reason that I didn't add `yarn.lock` to git is, I didn't want to make this project to depend on third-party package manager.

And I didn't add `package-lock.json` just because I didn't add `yarn.lock`

**Comment by hardtack** [comment]
@dhruvdutt 
I just created a issue for resource problem of `npm run watch`. (#40)
Lerna tries to run script serially when we don't give enough number of concurrency, So only `tsc --watch` of `@react-mdc/base` is executed when we don't give that. 🤦‍♂️
I'm trying to find nice way to integrate `tsc --watch` with lerna, but I couldn't find yet.

**Comment by dhruvdutt** [comment]
@Hardtack 
Can you please guide me setting up docs locally? 
[Quoting myself](https://github.com/react-mdc/react-material-components-web/pull/37#issuecomment-307023242) :smiley: 

> I did lerna bootstrap and then npm start inside docs directory. Everything is successfully executed but can't see any server running or hosting docs locally. Where/how to see them?

**Comment by hardtack** [comment]
@dhruvdutt 
Can you find a message like following after run `npm start`?
``` bash
> Document@0.1.3 start:webpack-dev-server /Users/owen/Development/Projects/react-material-compnents-web/docs
> webpack-dev-server --progress --config config/webpack/app.js

Project is running at http://localhost:8080/
```

It uses _webpack-dev-server_ for running server.
In my case, it binds server to `localhost:8080` automatically.

**Comment by dhruvdutt** [comment]
@Hardtack Yes! It works.

Actually the message `running at http://localhost:8080/` comes at 10% and there are lot of things popping on console till it completes 100%.

I missed that little line! My bad! Thanks!

**Pull request merged**
