### PR TITLE
Add className to Button's MetaProps

### PR DESCRIPTION
**Pull request by ukstv**
Fix error TS2559: Type 'MetaProps' has no properties in common with type 'ClassNameProps'.

### CODE REVIEW

**Comment by gutenye** [comment]
Also happens to other packages, like Toolbar, ...

**Comment by hardtack** [comment]
@ukstv cc. @gutenye
Hi, Thank you for your PR. 
I can't check this because I'm traveling now. 
I'll check this few days later. 

Actually, I already notice the possiblity of this bug. But my compiler didn't make errors so I didn't do anything. 
Could you tell me your environment? I want to reproduce this error on my machine before merge it.

**Comment by ukstv** [comment]
@Hardtack Here is it: https://gist.github.com/ukstv/dd07f217dfb3e73c776d6b7261d7b222

**Comment by sergeyzwezdin** [comment]
@Hardtack could you please complete this PR asap? Can't use button with this issue.

**Comment by hardtack** [comment]
Merged it. thanks!

**Comment by hardtack** [comment]
The problem was occurred by version of TS.
Type checking became more strict since 2.4 and I've fixed it in d158961eaba0c2608ee15c6677423804ee877c46

**Comment by sergeyzwezdin** [comment]
@Hardtack Nice work! Thank you for quick reaction.

**Pull request merged**
